services:

  mongodb:
    image: mongo:8.0.8
    restart: always
    container_name: eats-catalog
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: debuggeandoideas
      MONGO_INITDB_DATABASE: catalog
    ports:
      - "27017:27017"
    volumes:
    
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

